### ISSUE TITLE
Campaign is not working with Dotmailer

### ISSUE THREAD

**Issue by manh-nguyen** [oroinc/OroCRMDotmailerBundle#2]
Hi guys,

I created campaigns, address books, contacts on dotmailer server and sync them to OROCRM 1.8. Addressbook, contact have been synchronized to OROCRM but no campaign has been synchronized. 
On Dotmailer, I have 3 campaigns, one is in unsent box, the two others are in sent box.

Can you please tell me how to sync them to OROCRM?

Thanks and Best Regards,
Manh

**Comment by mkudelya** [comment]
Hi @manh-nguyen 

Sorry for not being in touch sooner. Are you still experiencing the issue with campaign import in the newest version of orocrm ?

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
